language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '6'
  - '8'
  - 'node'
install:
  - yarn install --frozen-lockfile
script:
  - yarn lint
  - yarn test:coverage --no-cache
  - yarn test:umd
after_success:
  - 'coveralls < coverage/lcov.info'
