language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "node"
before_script:
  - nvm install stable
  - npm run lint
  - nvm use $TRAVIS_NODE_VERSION
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
