version: 2.1

orbs:
  cypress: cypress-io/cypress@1.13.0
  node: circleci/node@1.1.6

jest-executor: &jest-executor
  executor:
    name: node/default
    tag: lts

jobs:
  test:
    <<: *jest-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn validate
      - run: yarn test --coverage --no-cache
      - run: yarn codecov
      - store_artifacts:
          path: lib
          destination: lib
      - store_artifacts:
          path: es
          destination: es
      - store_artifacts:
          path: dist
          destination: dist
  release:
    <<: *jest-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn semantic-release

workflows:
  test_and_release:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start-test-server
          wait-on: '--timeout 20000 http://localhost:5000'
      - test:
          requires:
            - cypress/run
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
